const positionsTable = `CREATE TABLE IF NOT EXISTS positions (
  positionID VARCHAR(255) PRIMARY KEY,
  label VARCHAR(100) NOT NULL,
  value VARCHAR(100) NOT NULL CHECK (value IN ('POSITIONS_STAFF', 'POSITIONS_ADMIN')),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);`;

export default positionsTable;
