const POSITIONS = {
  POSITIONS_MASTER_ADMIN: 'POSITIONS_MASTER_ADMIN',
  POSITIONS_HUMAN_RESOURCE: 'POSITIONS_HUMAN_RESOURCE',
  POSITIONS_STAFF: 'POSITIONS_STAFF'
}

const LABEL = {
  LABEL_MASTER_ADMIN: 'Master Admin',
  LABEL_HUMAN_RESOURCE: 'Human Resource',
  LABEL_STAFF: 'Staff'
}

const BLANK_VALUE = `-`

export {
  POSITIONS,
  LABEL,
  BLANK_VALUE
}